### ISSUE TITLE
Changer la font par défault, on utilisera maintenant `Inter` 

### ISSUE THREAD

**Issue by Bluzzi** [Virtual-Royaume/Royaume-Frontend#22]
- utiliser `Inter`
- download la font en local

**Comment by Steellgold** [comment]
✅ https://github.com/Virtual-Royaume/Royaume-Frontend/commit/8d45e05071bbd5573f165c844c8b948bdfc1d67f

![image](https://user-images.githubusercontent.com/51505384/227182014-7c209513-e9c1-4c35-a06d-0d0deaded9b8.png)
