### ISSUE TITLE
Nouveau système d'icon

### ISSUE THREAD

**Issue by Bluzzi** [Virtual-Royaume/Royaume-Frontend#24]
Tout les anciens icons (dans le dossier `/static`) doivent être déplacé dans le nouveau système d'icon `$lib/components/icons`.

Ce système d'icon doit utiliser une collection d'icon un maximum similaire. Chaque icon doit être un SVG. Les couleurs des icons doivent pouvoir être changer via une prop `color`, leur taille doit aussi pouvoir être changé via une prop `size` qui prend un nombre de pixel. 

Pouvoir visualiser la lib d'icon dans HistoireJS.

**Comment by Steellgold** [comment]
✅ https://github.com/Virtual-Royaume/Royaume-Frontend/commit/86fd8fe506035e774f572d3fdeaaae8baf6b880a

**Comment by Bluzzi** [comment]
Je suis pas sur que ça soit ok : 
- tu as fait un check global de tout les icons ? Voir si ils sont tous similaire (issue d'une même collection, ou presque)
- est-ce qu'ils sont tous visible sur HistoireJS ?

**Comment by Steellgold** [comment]
Tout est OK ✅
