### ISSUE TITLE
Correction de toutes les erreurs des actions GitHub 

### ISSUE THREAD

**Issue by Bluzzi** [Virtual-Royaume/Royaume-Frontend#25]

**Comment by Steellgold** [comment]
✅ 
- https://github.com/Virtual-Royaume/Royaume-Frontend/commit/a2abc437276c3a5034498eee96fdee4fbf4513e7
- https://github.com/Virtual-Royaume/Royaume-Frontend/commit/95c683f2abdc8092dade0454f80c427f641d14a8
