### ISSUE TITLE
Landing page 

### ISSUE THREAD

**Issue by Bluzzi** [Virtual-Royaume/Royaume-Frontend#5]
Une page d'accueil simple pour la pré-V1 qui comporte uniquement :
- Header
    - description de la communauté
    - couronne en 3D ?
    - bouton "nous rejoindre"
    - bouton "Github"
    - bouton "notre blog"
- Description de la communauté (mise en avant de nos "atouts")
    - Entraide
    - Projet et collaboration open source
    - Découvrir les technos du futur
    - Talk et call sur des sujets précis 
    - ...
- Liste des membres du Discord ![member list](https://user-images.githubusercontent.com/20624478/213881365-4e08bc8d-44cd-40c3-bf74-8178f97b0218.png)
- Quelques statistiques 
    - Nombre de message et temps de vocal par jour
    - ...
    - 
- Notre newsletter

**Comment by Steellgold** [comment]
C'est quoi page d'accueil "MVP" ?

**Comment by Bluzzi** [comment]
MVP veux dire "minimum viable product" ou "produit minimum viable" en français. 

C'est la page d'accueil et sachant que la première version sera principalement tourné vers le blog, il faudrait quelque chose de simple qui ne va pas prendre trop de temps à mettre en place.

**Comment by Bluzzi** [comment]
> C'est quoi page d'accueil "MVP" ?

MVP veux dire "minimum viable product" ou "produit minimum viable" en français.

C'est la page d'accueil et sachant que la première version sera principalement tourné vers le blog, il faudrait quelque chose de simple qui ne va pas prendre trop de temps à mettre en place.

**Comment by Steellgold** [comment]
Merci !

**Comment by nexty5870** [comment]
Mise en avant des talks organizer pour attirer les nouveau membres (c'est la killer feature je pense qui allie 'team building' / echange et attire du sang frais) - preparation de l'event avec Midjourney pour la promotion sur les reseau sociaux par example

Aspect communautaire sur les stats fournis par le bot discord a mettre en avant

Une section pour presentez chaque projet des membres (si projet dispo a presenter) peux etre pas mal pour attirer du monde

Courone 3D tournante a la Nux c'est upvote pour moi!
