### ISSUE TITLE
Mise en place de notre theme de couleur 

### ISSUE THREAD

**Issue by Bluzzi** [Virtual-Royaume/Royaume-Frontend#60]
Article intéressant : https://www.refactoringui.com/previews/building-your-color-palette

Il faut le documenter sur Storybook.

**Comment by Melvynx** [comment]
Faites attention avec cette article. Je les suivis pour Codeline et il m'arrive de regreetter, c'est moyen pratique pour les projets de taille petite moyenne

**Comment by Bluzzi** [comment]
Tkt on trouvera le juste milieu, je sais être pragmatique sur ce genre de point et j'ai déjà une bonne idée du juste milieu à prendre pour nous, j'ai eu l'occasion de mettre en place pas mal de design system dans mes dernières missions, j'ai plutôt conscience des pièges !

**Comment by Sakoutecher** [comment]
Je ne comprend pas bien, on doit réaliser un nouveau thème de couleur, ou alors ce baser sur les couleurs que l'on utilise actuellement sur le site ?

**Comment by Bluzzi** [comment]
L'objectif est d'avoir une palette de couleur complète tout en restant très structuré et compréhensible pour les devs (donc bien nommé, suffisamment mais pas trop de teinte, etc).

Il faut se baser sur les couleurs qu'on a actuellement mais en les diversifiant.

**Comment by Sakoutecher** [comment]
Donc si je comprend bien, on fais une palette de couleur avec nos couleurs mais donc avec des variantes de nos couleurs ?

**Comment by Bluzzi** [comment]
Yes c'est ça !

**Comment by Sakoutecher** [comment]
Je vais regarder l'article et voir si j'arrive à faire quelque chose de cool ! On fais une sortes de doc avec Storybook ?

**Comment by Bluzzi** [comment]
Yes, mais dans un premier temps faudrait que tout le monde soit d'accord sur la palette et qu'on test d'adapter le site qu'on a déjà avec celle-ci voir si ça match en condition réel !
